FROM nginx:alpine

# Instalar Tailscale
RUN apk add --no-cache tailscale

# Copiar el script de inicio
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Exponer el puerto de Nginx
EXPOSE 80

# Iniciar mediante el script
CMD ["/start.sh"]
